-- Create private_messages table
create table if not exists private_messages (
  id bigint generated by default as identity primary key,
  sender_id uuid references auth.users(id) not null,
  receiver_id uuid references auth.users(id) not null,
  content text not null,
  related_hop_id bigint references hoppings(id) on delete set null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table private_messages enable row level security;

-- Policy: Users can see messages they sent or received
create policy "Users can view their own messages"
  on private_messages for select
  using ( auth.uid() = sender_id or auth.uid() = receiver_id );

-- Policy: Users can send messages
create policy "Users can insert messages"
  on private_messages for insert
  with check ( auth.uid() = sender_id );
