-- Create bar_owners table for Many-to-Many relationship
create table if not exists bar_owners (
  id bigint generated by default as identity primary key,
  bar_id bigint references bars(id) on delete cascade not null,
  user_id uuid references users(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(bar_id, user_id)
);

-- Enable RLS
alter table bar_owners enable row level security;

-- Policies
create policy "Public bar_owners viewable by everyone" 
  on bar_owners for select 
  using (true);

create policy "Authenticated users can insert bar_owners" 
  on bar_owners for insert 
  with check (auth.role() = 'authenticated');

create policy "Authenticated users can delete bar_owners" 
  on bar_owners for delete 
  using (auth.role() = 'authenticated');

-- Migrate existing owners
insert into bar_owners (bar_id, user_id)
select id, owner_user_id 
from bars 
where owner_user_id is not null
on conflict (bar_id, user_id) do nothing;
