-- Ensure Menus are public
create table if not exists menus (
  id bigint generated by default as identity primary key,
  bar_id bigint references bars(id) on delete cascade not null,
  title_zh text,
  title_en text,
  file_url text,
  description_zh text,
  description_en text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table menus enable row level security;
drop policy if exists "Public menus are viewable by everyone" on menus;
create policy "Public menus are viewable by everyone" on menus for select using (true);

-- Ensure Events are public
create table if not exists events (
  id bigint generated by default as identity primary key,
  bar_id bigint references bars(id) on delete cascade not null,
  title_zh text,
  title_en text,
  start_date_time timestamp with time zone,
  end_date_time timestamp with time zone,
  cover_image text,
  booking_url text,
  description_zh text,
  description_en text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table events enable row level security;
drop policy if exists "Public events are viewable by everyone" on events;
create policy "Public events are viewable by everyone" on events for select using (true);

-- Ensure Bar Gallery is public
create table if not exists bar_gallery (
  id bigint generated by default as identity primary key,
  bar_id bigint references bars(id) on delete cascade not null,
  image_url text not null,
  sort_order integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table bar_gallery enable row level security;
drop policy if exists "Public bar_gallery is viewable by everyone" on bar_gallery;
create policy "Public bar_gallery is viewable by everyone" on bar_gallery for select using (true);

-- Ensure Bar Owners table is readable
drop policy if exists "Public bar_owners viewable by everyone" on bar_owners;
create policy "Public bar_owners viewable by everyone" on bar_owners for select using (true);
