-- Re-run creation of hopping_cheers table to fix 404 errors
create table if not exists hopping_cheers (
  id bigint generated by default as identity primary key,
  hopping_id bigint references hoppings(id) on delete cascade not null,
  user_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(hopping_id, user_id)
);

-- Enable RLS
alter table hopping_cheers enable row level security;

-- Drop existing policies to avoid conflicts if they partially exist
drop policy if exists "Public cheers are viewable by everyone." on hopping_cheers;
drop policy if exists "Authenticated users can cheer." on hopping_cheers;
drop policy if exists "Users can un-cheer (delete)." on hopping_cheers;

-- Re-create Policies
create policy "Public cheers are viewable by everyone."
  on hopping_cheers for select
  using ( true );

create policy "Authenticated users can cheer."
  on hopping_cheers for insert
  with check ( auth.uid() = user_id );

create policy "Users can un-cheer (delete)."
  on hopping_cheers for delete
  using ( auth.uid() = user_id );
