-- Drop table if exists to ensure schema update
drop table if exists hopping_comments cascade;

-- Create hopping_comments table
create table hopping_comments (
  id bigint generated by default as identity primary key,
  hopping_id bigint references hoppings(id) on delete cascade not null,
  user_id uuid references users(id) not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table hopping_comments enable row level security;

-- Policies
create policy "Public comments are viewable by everyone."
  on hopping_comments for select
  using ( true );

create policy "Authenticated users can insert comments."
  on hopping_comments for insert
  with check ( auth.role() = 'authenticated' );

-- Users can delete their own comments OR the Hop Owner can delete comments on their hop
create policy "Users can delete comments (author or hop owner)."
  on hopping_comments for delete
  using ( 
    auth.uid() = user_id 
    OR 
    exists (
      select 1 from hoppings 
      where hoppings.id = hopping_comments.hopping_id 
      and hoppings.user_id = auth.uid()
    )
  );
