-- Create hoppings table
create table if not exists hoppings (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  bar_id bigint references bars(id) on delete cascade not null,
  image_url text not null,
  rating integer check (rating >= 1 and rating <= 5),
  description text,
  is_public boolean default true,
  hopped_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table hoppings enable row level security;

-- Policies
create policy "Public hoppings are viewable by everyone."
  on hoppings for select
  using ( is_public = true or auth.uid() = user_id );

create policy "Users can insert their own hoppings."
  on hoppings for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own hoppings."
  on hoppings for update
  using ( auth.uid() = user_id );
