-- Create table tracking cheers/likes on hopping cards
create table if not exists hopping_cheers (
  id bigint generated by default as identity primary key,
  hopping_id bigint references hoppings(id) on delete cascade not null,
  user_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(hopping_id, user_id)
);

-- Enable RLS
alter table hopping_cheers enable row level security;

-- Policies
create policy "Public cheers are viewable by everyone."
  on hopping_cheers for select
  using ( true );

create policy "Authenticated users can cheer."
  on hopping_cheers for insert
  with check ( auth.uid() = user_id );

create policy "Users can un-cheer (delete)."
  on hopping_cheers for delete
  using ( auth.uid() = user_id );
