-- Drop table if exists to ensure schema update (e.g. FK changes)
drop table if exists hopping_comments cascade;

-- Create hopping_comments table
-- Note: Referencing public.users(id) to allow PostgREST joins for profile data.
create table hopping_comments (
  id bigint generated by default as identity primary key,
  hopping_id bigint references hoppings(id) on delete cascade not null,
  user_id uuid references users(id) not null, -- Changed from auth.users to public.users for Join capability
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table hopping_comments enable row level security;

-- Policies
create policy "Public comments are viewable by everyone."
  on hopping_comments for select
  using ( true );

create policy "Authenticated users can insert comments."
  on hopping_comments for insert
  with check ( auth.role() = 'authenticated' );

-- Users can delete their own comments
create policy "Users can delete their own comments."
  on hopping_comments for delete
  using ( auth.uid() = user_id );
