-- 1. Create 'awards' master table
create table if not exists public.awards (
  id bigint generated by default as identity primary key,
  name text not null,
  year integer not null,
  type text not null check (type in ('ranking', 'selection')),
  subtype_options text[], -- Array of strings for selection types (e.g. ['1 Star', 'Recommended'])
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Clean up old 'bar_awards' (Drop to re-create structure)
-- WARNING: This deletes existing award data as per plan.
drop table if exists public.bar_awards;

-- 3. Re-create 'bar_awards' with new relationship
create table public.bar_awards (
  id bigint generated by default as identity primary key,
  bar_id bigint references public.bars(id) on delete cascade not null,
  award_id bigint references public.awards(id) on delete cascade not null,
  rank text, -- Stores the Rank Number (e.g. "5") or Selection Tier (e.g. "1 Star")
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(bar_id, award_id) -- Prevent duplicate entries for same award
);

-- 4. Enable RLS
alter table public.awards enable row level security;
alter table public.bar_awards enable row level security;

-- 5. Policies for 'awards'
-- Public read
create policy "Public awards are viewable by everyone."
  on public.awards for select
  using ( true );

-- Admin/Editor write (Restricted)
create policy "Admins/Editors can insert awards."
  on public.awards for insert
  with check ( 
    exists (
      select 1 from public.users 
      where id = auth.uid() 
      and (roles @> array['admin'] or roles @> array['editor'])
    )
  );

create policy "Admins/Editors can update awards."
  on public.awards for update
  using ( 
    exists (
      select 1 from public.users 
      where id = auth.uid() 
      and (roles @> array['admin'] or roles @> array['editor'])
    )
  );

create policy "Admins/Editors can delete awards."
  on public.awards for delete
  using ( 
    exists (
      select 1 from public.users 
      where id = auth.uid() 
      and (roles @> array['admin'] or roles @> array['editor'])
    )
  );

-- 6. Policies for 'bar_awards'
-- Public read
create policy "Public bar_awards are viewable by everyone."
  on public.bar_awards for select
  using ( true );

-- Admin/Editor write (Owners cannot self-assign)
create policy "Admins/Editors can insert bar_awards."
  on public.bar_awards for insert
  with check ( 
    exists (
      select 1 from public.users 
      where id = auth.uid() 
      and (roles @> array['admin'] or roles @> array['editor'])
    )
  );

create policy "Admins/Editors can update bar_awards."
  on public.bar_awards for update
  using ( 
    exists (
      select 1 from public.users 
      where id = auth.uid() 
      and (roles @> array['admin'] or roles @> array['editor'])
    )
  );

create policy "Admins/Editors can delete bar_awards."
  on public.bar_awards for delete
  using ( 
    exists (
      select 1 from public.users 
      where id = auth.uid() 
      and (roles @> array['admin'] or roles @> array['editor'])
    )
  );
