-- Create article_bars table for Many-to-Many relationship
create table if not exists article_bars (
  id bigint generated by default as identity primary key,
  article_id bigint references articles(id) on delete cascade not null,
  bar_id bigint references bars(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(article_id, bar_id)
);

-- Enable RLS
alter table article_bars enable row level security;

-- Policies
-- Public read access
create policy "Public article_bars are viewable by everyone."
  on article_bars for select
  using ( true );

-- Authenticated users can insert/update/delete (or restrict to admin/editor if needed)
create policy "Users can insert article_bars."
  on article_bars for insert
  with check ( auth.role() = 'authenticated' );

create policy "Users can update article_bars."
  on article_bars for update
  using ( auth.role() = 'authenticated' );

create policy "Users can delete article_bars."
  on article_bars for delete
  using ( auth.role() = 'authenticated' );

-- Add all missing columns to bars (Consolidated)
alter table bars 
add column if not exists title text,
add column if not exists description text,
add column if not exists vibe text,
add column if not exists location text,
add column if not exists image text,
add column if not exists price integer default 2,
add column if not exists instagram_url text,
add column if not exists facebook_url text,
add column if not exists website_url text,
add column if not exists owner_name text,
add column if not exists bartender_name text,
add column if not exists opening_hours text,
add column if not exists phone text,
add column if not exists menu_url text,
add column if not exists is_published boolean default true,
add column if not exists address text,
add column if not exists lat double precision,
add column if not exists lng double precision,
add column if not exists google_map_url text,
add column if not exists google_rating numeric,
add column if not exists google_review_count integer,
add column if not exists editorial_rating integer,
add column if not exists editorial_review text;

-- Add image_caption to articles
alter table articles
add column if not exists image_caption text;

-- Create bar_images table for Gallery
create table if not exists bar_images (
  id bigint generated by default as identity primary key,
  bar_id bigint references bars(id) on delete cascade not null,
  image_url text not null,
  caption text,
  display_order integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for bar_images
alter table bar_images enable row level security;

-- Policies for bar_images
create policy "Public bar_images are viewable by everyone."
  on bar_images for select
  using ( true );

create policy "Users can insert bar_images."
  on bar_images for insert
  with check ( auth.role() = 'authenticated' );

create policy "Users can update bar_images."
  on bar_images for update
  using ( auth.role() = 'authenticated' );

create policy "Users can delete bar_images."
  on bar_images for delete
  using ( auth.role() = 'authenticated' );

-- Create signatures table
create table if not exists signatures (
  id bigint generated by default as identity primary key,
  bar_id bigint references bars(id) on delete cascade not null,
  name text not null,
  description text,
  price text,
  review text,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for signatures
alter table signatures enable row level security;

-- Policies for signatures
create policy "Public signatures are viewable by everyone."
  on signatures for select
  using ( true );

create policy "Users can insert signatures."
  on signatures for insert
  with check ( auth.role() = 'authenticated' );

create policy "Users can update signatures."
  on signatures for update
  using ( auth.role() = 'authenticated' );

create policy "Users can delete signatures."
  on signatures for delete
  using ( auth.role() = 'authenticated' );

-- Create bar_awards table
create table if not exists bar_awards (
  id bigint generated by default as identity primary key,
  bar_id bigint references bars(id) on delete cascade not null,
  name text not null,
  rank text,
  year integer,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table bar_awards enable row level security;

-- Policies
create policy "Public bar_awards are viewable by everyone."
  on bar_awards for select
  using ( true );

create policy "Authenticated users can insert bar_awards."
  on bar_awards for insert
  with check ( auth.role() = 'authenticated' );

create policy "Authenticated users can update bar_awards."
  on bar_awards for update
  using ( auth.role() = 'authenticated' );

create policy "Authenticated users can delete bar_awards."
  on bar_awards for delete
  using ( auth.role() = 'authenticated' );

-- Add start_date and end_date to articles for Event category
alter table articles
add column if not exists start_date timestamp with time zone,
add column if not exists end_date timestamp with time zone;
