-- Create article_bars table for Many-to-Many relationship
drop table if exists article_bars cascade;
create table if not exists article_bars (
  id bigint generated by default as identity primary key,
  article_id bigint references articles(id) on delete cascade not null,
  bar_id bigint references bars(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(article_id, bar_id)
);

-- Enable RLS
alter table article_bars enable row level security;

-- Policies
-- Public read access
create policy "Public article_bars are viewable by everyone."
  on article_bars for select
  using ( true );

-- Authenticated users can insert/update/delete (or restrict to admin/editor if needed)
create policy "Users can insert article_bars."
  on article_bars for insert
  with check ( auth.role() = 'authenticated' );

create policy "Users can update article_bars."
  on article_bars for update
  using ( auth.role() = 'authenticated' );

create policy "Users can delete article_bars."
  on article_bars for delete
  using ( auth.role() = 'authenticated' );
