-- Create article_bars table for Many-to-Many relationship
create table if not exists article_bars (
  id bigint generated by default as identity primary key,
  article_id bigint references articles(id) on delete cascade not null,
  bar_id bigint references bars(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(article_id, bar_id)
);

-- Enable RLS
alter table article_bars enable row level security;

-- Policies
-- Public read access
create policy "Public article_bars are viewable by everyone."
  on article_bars for select
  using ( true );

-- Authenticated users can insert/update/delete (or restrict to admin/editor if needed)
create policy "Users can insert article_bars."
  on article_bars for insert
  with check ( auth.role() = 'authenticated' );

create policy "Users can update article_bars."
  on article_bars for update
  using ( auth.role() = 'authenticated' );

create policy "Users can delete article_bars."
  on article_bars for delete
  using ( auth.role() = 'authenticated' );

-- Add all missing columns to bars (Consolidated)
alter table bars 
add column if not exists title text,
add column if not exists description text,
add column if not exists vibe text,
add column if not exists location text,
add column if not exists image text,
add column if not exists price integer default 2,
add column if not exists instagram_url text,
add column if not exists facebook_url text,
add column if not exists website_url text,
add column if not exists owner_name text,
add column if not exists bartender_name text,
add column if not exists opening_hours text,
add column if not exists phone text,
add column if not exists menu_url text,
add column if not exists is_published boolean default true,
add column if not exists address text,
add column if not exists lat double precision,
add column if not exists lng double precision,
add column if not exists google_map_url text,
add column if not exists google_rating numeric,
add column if not exists google_review_count integer,
add column if not exists editorial_rating integer,
add column if not exists editorial_review text;

-- Add image_caption to articles
alter table articles
add column if not exists image_caption text;

-- Create bar_images table for Gallery
create table if not exists bar_images (
  id bigint generated by default as identity primary key,
  bar_id bigint references bars(id) on delete cascade not null,
  image_url text not null,
  caption text,
  display_order integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for bar_images
alter table bar_images enable row level security;

-- Policies for bar_images
create policy "Public bar_images are viewable by everyone."
  on bar_images for select
  using ( true );

create policy "Users can insert bar_images."
  on bar_images for insert
  with check ( auth.role() = 'authenticated' );

create policy "Users can update bar_images."
  on bar_images for update
  using ( auth.role() = 'authenticated' );

create policy "Users can delete bar_images."
  on bar_images for delete
  using ( auth.role() = 'authenticated' );

-- Create signatures table
create table if not exists signatures (
  id bigint generated by default as identity primary key,
  bar_id bigint references bars(id) on delete cascade not null,
  name text not null,
  description text,
  price text,
  review text,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for signatures
alter table signatures enable row level security;

-- Policies for signatures
create policy "Public signatures are viewable by everyone."
  on signatures for select
  using ( true );

create policy "Users can insert signatures."
  on signatures for insert
  with check ( auth.role() = 'authenticated' );

create policy "Users can update signatures."
  on signatures for update
  using ( auth.role() = 'authenticated' );

create policy "Users can delete signatures."
  on signatures for delete
  using ( auth.role() = 'authenticated' );

-- Create bar_awards table
create table if not exists bar_awards (
  id bigint generated by default as identity primary key,
  bar_id bigint references bars(id) on delete cascade not null,
  name text not null,
  rank text,
  year integer,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table bar_awards enable row level security;

-- Policies
create policy "Public bar_awards are viewable by everyone."
  on bar_awards for select
  using ( true );

create policy "Authenticated users can insert bar_awards."
  on bar_awards for insert
  with check ( auth.role() = 'authenticated' );

create policy "Authenticated users can update bar_awards."
  on bar_awards for update
  using ( auth.role() = 'authenticated' );

create policy "Authenticated users can delete bar_awards."
  on bar_awards for delete
  using ( auth.role() = 'authenticated' );

-- Add start_date and end_date to articles for Event category
alter table articles
add column if not exists start_date timestamp with time zone,
add column if not exists end_date timestamp with time zone,
add column if not exists category text;

-- Create a table for public profiles (synced with auth.users)
create table if not exists users (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  name text,
  roles text[] default array['reader'], -- 'admin', 'editor', 'barOwner', 'reader'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table users enable row level security;

-- Policies (Drop first to avoid "already exists" error)
drop policy if exists "Public profiles are viewable by everyone." on users;
create policy "Public profiles are viewable by everyone."
  on users for select
  using ( true );

drop policy if exists "Users can insert their own profile." on users;
create policy "Users can insert their own profile."
  on users for insert
  with check ( auth.uid() = id );

drop policy if exists "Users can update own profile." on users;
create policy "Users can update own profile."
  on users for update
  using ( auth.uid() = id );

-- Internal function to handle new user entries
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.users (id, email, name, roles)
  values (new.id, new.email, split_part(new.email, '@', 1), array['reader']);
  return new;
end;
$$;

-- Trigger to call the function on signup
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- FIX: Enable RLS and Add Policies for main tables
-- This ensures that the Admin Dashboard can actually SEE the data.

-- BARS Table Policies
alter table bars enable row level security;

drop policy if exists "Public bars are viewable by everyone." on bars;
create policy "Public bars are viewable by everyone."
  on bars for select
  using ( true );

drop policy if exists "Authenticated users can insert bars." on bars;
create policy "Authenticated users can insert bars."
  on bars for insert
  with check ( auth.role() = 'authenticated' );

drop policy if exists "Authenticated users can update bars." on bars;
create policy "Authenticated users can update bars."
  on bars for update
  using ( auth.role() = 'authenticated' );

drop policy if exists "Authenticated users can delete bars." on bars;
create policy "Authenticated users can delete bars."
  on bars for delete
  using ( auth.role() = 'authenticated' );

-- ARTICLES Table Policies
alter table articles enable row level security;

drop policy if exists "Public articles are viewable by everyone." on articles;
create policy "Public articles are viewable by everyone."
  on articles for select
  using ( true );

drop policy if exists "Authenticated users can insert articles." on articles;
create policy "Authenticated users can insert articles."
  on articles for insert
  with check ( auth.role() = 'authenticated' );

drop policy if exists "Authenticated users can update articles." on articles;
create policy "Authenticated users can update articles."
  on articles for update
  using ( auth.role() = 'authenticated' );

drop policy if exists "Authenticated users can delete articles." on articles;
create policy "Authenticated users can delete articles."
  on articles for delete
  using ( auth.role() = 'authenticated' );
